import { applicationDrafts, damageAssessments, workflows } from '../data/mockData';
import type { AgentWorkflow, ApplicationDraft, DamageAssessment } from '../types';

const delay = async (ms: number) => new Promise((resolve) => window.setTimeout(resolve, ms));

export const getDamageAssessments = async (): Promise<DamageAssessment[]> => {
  await delay(220);
  // Future AWS integration: replace with an API Gateway or Lambda-backed fetch call.
  return damageAssessments;
};

export const assessDamage = async (imageUrl: string): Promise<DamageAssessment> => {
  await delay(260);
  // Future AWS integration: send image metadata to the Bedrock-powered classification endpoint.
  return {
    ...damageAssessments[0],
    afterImage: imageUrl || damageAssessments[0].afterImage,
  };
};

export const matchAidPrograms = async (payload: {
  buildingId: string;
  estimatedDamage: string;
  evidenceTags: string[];
}): Promise<ApplicationDraft['aidPrograms']> => {
  await delay(180);
  // Future AWS integration: call a policy-matching service that scores programs from FEMA guidance.
  return applicationDrafts.find((draft) => draft.buildingId === payload.buildingId)?.aidPrograms ?? [];
};

export const getApplicationDraft = async (buildingId: string): Promise<ApplicationDraft> => {
  await delay(240);
  // Future AWS integration: fetch the drafted application generated by the Bedrock orchestration layer.
  return (
    applicationDrafts.find((draft) => draft.buildingId === buildingId) ??
    applicationDrafts[0]
  );
};

export const runAgentWorkflow = async (buildingId: string): Promise<AgentWorkflow> => {
  await delay(210);
  // Future AWS integration: retrieve live agent trace events from a workflow execution endpoint.
  return workflows.find((workflow) => workflow.buildingId === buildingId) ?? workflows[0];
};
